const { viewMore } = require('./zh');

module.exports = {
  hello: 'hello，welcome to MIOT Extension development !',
  selfDefineScene: 'custom scene',
  timeSetting: 'time setting',
  countDownTime: 'countdown time',
  workModel: 'Operating mode',
  currentMatch: 'current match',
  IndicatorLightStatus: 'light status',
  acid2: 'DianXiaoKu AC Partner CP2pro',
  acid3: 'On/Off',
  acid4: 'Quick-cool',
  acid5: 'Quick cooling time',
  acid6:
    'Once enabled,the air conditioner is set to maximum fan speed and minimum temperature, and restore the temperature of the last shutdown after the specified time.',
  acid7: 'Sleep period',
  acid8:
    'Note：This function is only effective while the air conditioner is cooling or heating.',
  acid9: 'After sleep',
  acid10: 'Keep the current status',

  acid11: 'Turn off  air conditioner',
  acid12: 'Delay turn off time',
  acid13: 'Automatically adapts to running mode',
  acid14: 'Temp adjustment',
  acid15: 'Fan speed',
  acid16: 'Auto',
  acid17: 'Low',
  acid18: 'Medium',
  acid19: 'High',
  acid20: 'Swing',

  acid21: 'Mode',
  acid22: 'Cooling',
  acid23: 'Heating',
  acid24: 'Auto',
  acid25: 'Air supply',
  acid26: 'Dry',
  acid27: 'Sleeping mode',
  acid28: 'Schedules',
  acid29: 'Delay turning off',
  acid30: 'Work mode',

  acid31: 'The AC is plugged into a socket',
  acid32: 'The AC is not plugged in',
  acid33: 'Current pairing',
  acid34: 'Indicator status',
  acid35: 'Indicator setting',
  acid36: 'Indicator on/of',
  acid37: 'Do not disturb mode',
  acid38: 'Start time',
  acid39: 'The device turns off the indicator light at this time',
  acid40: 'End time',

  acid41: 'The device turns on the indicator light at this time',
  acid42: 'Today(KWH)',
  acid43: 'Current  (W)',
  acid44: 'Week(KWH)',
  acid45: 'Month(KWH)',
  acid46: 'Switching frequency',
  acid47: "Today's Switch Log",
  acid48: 'ON',
  acid49: 'OFF',
  acid50: 'No operation',
  acid51: 'Ok',

  acid52: 'Change paired air conditioner',
  acid53:
    'After replacement, the set  schedules, and created automation will continue to be in effect. However, since there are functional differences between different air conditioners, these settings may not take effect.',
  acid54: 'Cancel',
  acid55: 'End time',
  acid56: 'Tomorrow',
  acid57: 'The start time and end time must be different',
  acid58: 'Week',
  acid59: 'Month',
  acid60: 'Year',
  acid61: 'Day',
  acid62: 'KWH',

  acid63: 'Comfortable mode',
  acid64: 'Cooling mode',
  acid65: 'Temp adjustment',
  acid66: 'Panel Brightness',
  acid67: 'Sleeping mode',
  acid68: 'Delay turning off',
  acid69: 'Swing On',
  acid70: 'Swing Off',

  acid71:
    'Air conditioner will change status according to your setting when turn on ',
  acid72: 'One time',
  acid73: 'Automatically adapts to running mode',
  acid74: 'Low',
  acid76: 'Repeat',
  acid77: 'Workday',
  acid78: 'Everyday',
  acid79: 'Weekend',
  acid80: 'Custom',
  acid81: 'Repetition',
  acid82: 'Customize Repetition',
  acid83: 'Monday',
  acid84: 'Tuesday',
  acid85: 'Wednesday',
  acid86: 'Thursday',
  acid87: 'Friday',
  acid88: 'Saturday',
  acid89: 'Sunday',
  acid90: 'High',
  acid91: 'Medium',
  acid92: 'Low',
  acid93: 'Delay turning off time',

  acid94: 'min',

  acid95: 'to',
  acid96: 'Electricity consumption statistics',
  acid97: 'Quick cooling curve',
  acid98: 'Indoor Temperature',
  acid99: 'Last temperature before turning off',
  acid100: 'h later',
  acid101: 'min later',
  acid102: 'Duration can not be less than two hours',

  acid103: 'Tap the button and confirm whether the air conditioner responds',
  acid104:
    'The device needs some time to respond, please wait a moment after the operation',

  acid108: 'Is the appliance paired correctly?',
  acid109: 'Incorrect',
  acid110: 'Correct',

  acid114: 'Paired successfully! Try it now!',
  acid115: 'Done',
  acid116: 'Your infrared code can not be paired.',
  acid117: 'Loading, please wait a moment.',
  acid118: 'Power on',
  acid119: 'Power off',
  acid120: 'Matching air conditioning',
  acid121: 'Brand list',
  acid122: 'Search brand',
  acid123:
    'Air conditioners without a status disaplay do not support this function.',
  acid124: 'Setting',
  acid126: 'Enter',
  acid127: 'Do not disturb',
  acid128: 'Holidays',
  acid129: 'Working days',
  acid130: 'Next day',
  acid131: 'Every day',
  acid132: 'Enable',
  acid133: 'h',
  acid134: 'Running',
  acid135: 'Comfortable',
  acid136: 'Cooling',
  acid137: 'Select month',

  viewMore: 'View more'
};
